// Generated by tools/train_and_quantize.py — do not edit by hand.
// Run the training script to populate model_data.cpp with the real
// INT8-quantized TFLite Micro model bytes before flashing.
#pragma once

extern const unsigned char g_model_data[];
extern const int g_model_data_len;
